apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal
  title: My Portfolio Developer Portal
  description: The central hub for all my projects and documentation.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: guests
  lifecycle: production
