apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: shrinet82
  description: Platform admin
spec:
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mad82-ops
  description: Developer
spec:
  memberOf: [developers]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: Development Team
spec:
  type: team
  children: []
