apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    'github.com/project-slug': '${{ values.destination.owner }}/${{ values.destination.repo }}'
    'backstage.io/techdocs-ref': 'dir:.'
    'argocd/app-name': '${{ values.component_id }}'
    'backstage.io/kubernetes-id': '${{ values.component_id }}'
    'backstage.io/kubernetes-namespace': 'default'
    'grafana/overview-dashboard': 'http://143.110.177.137:32395/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&kiosk'
  tags:
    - go
    - golang
    - argocd
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
